
{{- if and .Values.__services .Values.serviceName}}
{{- $serviceMap := index .Values.__services .Values.serviceName}}
{{- $serviceType := index $serviceMap "type"}}

apiVersion: v1
kind: Service

metadata:
    name: {{.Values.serviceName}}
    labels:
        run: {{.Values.serviceName}}
    namespace: {{.Values.namespace | lower}}

spec:
    type: {{$serviceType}}
    selector:
        run: {{.Values.serviceName}}
    ports:
      - port: {{index $serviceMap "external_port"}}
        protocol: TCP
        targetPort: {{index $serviceMap "container_port"}}
    {{- if eq $serviceType "LoadBalancer"}}
    loadBalancerIP: {{index $serviceMap "host"}}
    {{- end}}
{{- end}}

