##---
# Source: skillhub/templates/deployment-config-os.yaml


apiVersion: v1
kind: DeploymentConfig

metadata:
    name: backend
    labels:
        app: skillhub
        run: backend

spec:
    replicas: 1
    selector:
        run: backend
    template:
        metadata:
            labels:
                run: backend
        spec:
            containers:
            - name: backend
              image: docker-registry.default.svc:5000/skillhub/backend:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 5000

              env:
              - name: BACKEND_PORT
                value: "80"
              - name: BACKEND_HOST
                value: "backend-skillhub.apps.ic.gc.ca"
              - name: BACKEND_DATABASE_PORT
                value: "5432"
              - name: BACKEND_DATABASE_HOST
                value: "backend-database"
              - name: FRONTEND_PORT
                value: "80"
              - name: FRONTEND_HOST
                value: "skillhub.apps.ic.gc.ca"
              - name: PREDICTIONS_PORT
                value: "80"
              - name: PREDICTIONS_HOST
                value: "predictions-skillhub.apps.ic.gc.ca"
              - name: REDIS_PORT
                value: "6379"
              - name: REDIS_HOST
                value: "redis"
              - name: SCRAPER_PORT
                value: "80"
              - name: SCRAPER_HOST
                value: "scraper-skillhub.apps.ic.gc.ca"
              - name: SCRAPER_JOB_PORT
                value: 
              - name: SCRAPER_JOB_HOST
                value: 
              - name: SCRAPER_WORKER_PORT
                value: 
              - name: SCRAPER_WORKER_HOST
                value: 
              - name: PREDICTIONS_PROTOCOL
                value: "https"
              - name: PREDICTIONS_API_KEY
                valueFrom:
                    secretKeyRef:
                        name: backend-secrets
                        key: PREDICTIONS_API_KEY
              - name: SCRAPER_API_KEY
                valueFrom:
                    secretKeyRef:
                        name: backend-secrets
                        key: SCRAPER_API_KEY
              - name: TOKEN_SECRET
                valueFrom:
                    secretKeyRef:
                        name: backend-secrets
                        key: TOKEN_SECRET
            initContainers:
              - name: wait-for-service
                image: busybox
                command: ["sh", "-c", "until nslookup backend-database; do echo waiting for backend-database; sleep 2; done;"]
              - name: pre-startup
                image: docker-registry.default.svc:5000/skillhub/backend:latest
                command: ["sh", "-c", "npm run db:retryable-migrate && npm run db:seed"]
                env:
                  - name: PREDICTIONS_PROTOCOL
                    value: "https"

    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
          automatic: true
          containerNames:
          - backend
          from:
              kind: ImageStreamTag
              name: "backend:latest"
