##---
# Source: skillhub/templates/deployment-config-os.yaml


apiVersion: v1
kind: DeploymentConfig

metadata:
    name: frontend
    labels:
        app: skillhub
        run: frontend

spec:
    replicas: 1
    selector:
        run: frontend
    template:
        metadata:
            labels:
                run: frontend
        spec:
            containers:
            - name: frontend
              image: docker-registry.default.svc:5000/skillhub/frontend:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 3000

              env:
              - name: BACKEND_PORT
                value: "80"
              - name: BACKEND_HOST
                value: "backend-skillhub.apps.ic.gc.ca"
              - name: BACKEND_DATABASE_PORT
                value: "5432"
              - name: BACKEND_DATABASE_HOST
                value: "backend-database"
              - name: FRONTEND_PORT
                value: "80"
              - name: FRONTEND_HOST
                value: "skillhub.apps.ic.gc.ca"
              - name: PREDICTIONS_PORT
                value: "80"
              - name: PREDICTIONS_HOST
                value: "predictions-skillhub.apps.ic.gc.ca"
              - name: REDIS_PORT
                value: "6379"
              - name: REDIS_HOST
                value: "redis"
              - name: SCRAPER_PORT
                value: "80"
              - name: SCRAPER_HOST
                value: "scraper-skillhub.apps.ic.gc.ca"
              - name: SCRAPER_JOB_PORT
                value: 
              - name: SCRAPER_JOB_HOST
                value: 
              - name: SCRAPER_WORKER_PORT
                value: 
              - name: SCRAPER_WORKER_HOST
                value: 
              - name: NODE_ENV
                value: "production"

    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
          automatic: true
          containerNames:
          - frontend
          from:
              kind: ImageStreamTag
              name: "frontend:latest"
