---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: skillhub
  namespace: cert-manager
spec:
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - skillhub.ca
      - '*.skillhub.ca'
      - '*.backend.skillhub.ca'
  dnsNames:
  - skillhub.ca
  - '*.skillhub.ca'
  - '*.backend.skillhub.ca'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: skillhub-tls
