##---
# Source: skillhub/templates/deployment-config-os.yaml


apiVersion: v1
kind: DeploymentConfig

metadata:
    name: scraper
    labels:
        app: skillhub
        run: scraper

spec:
    replicas: 1
    selector:
        run: scraper
    template:
        metadata:
            labels:
                run: scraper
        spec:
            containers:
            - name: scraper
              image: docker-registry.default.svc:5000/skillhub/scraper:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 5000

              env:
              - name: BACKEND_PORT
                value: "80"
              - name: BACKEND_HOST
                value: "backend-skillhub.apps.ic.gc.ca"
              - name: BACKEND_DATABASE_PORT
                value: "5432"
              - name: BACKEND_DATABASE_HOST
                value: "backend-database"
              - name: FRONTEND_PORT
                value: "80"
              - name: FRONTEND_HOST
                value: "skillhub.apps.ic.gc.ca"
              - name: PREDICTIONS_PORT
                value: "80"
              - name: PREDICTIONS_HOST
                value: "predictions-skillhub.apps.ic.gc.ca"
              - name: REDIS_PORT
                value: "6379"
              - name: REDIS_HOST
                value: "redis"
              - name: SCRAPER_PORT
                value: "80"
              - name: SCRAPER_HOST
                value: "scraper-skillhub.apps.ic.gc.ca"
              - name: SCRAPER_WORKER_PORT
                value: 
              - name: SCRAPER_WORKER_HOST
                value: 
              - name: GIT_PLATFORM
                value: "bitbucket"
              - name: GIT_HOST
                value: "https://asbscr.ic.gc.ca/scm"
              - name: JIRA_HOST
                value: "http://jira.ic.gc.ca"
              - name: JIRA_PLATFORM
                value: "server"
              - name: BACKEND_PROTOCOL
                value: "https"
              - name: PROXY_HOST
                value: "cdhwg01.prod.prv"
              - name: PROXY_PORT
                value: "80"
              - name: GIT_AUTH_TOKEN
                valueFrom:
                    secretKeyRef:
                        name: scraper-secrets
                        key: GIT_AUTH_TOKEN
              - name: JIRA_AUTH_TOKEN
                valueFrom:
                    secretKeyRef:
                        name: scraper-secrets
                        key: JIRA_AUTH_TOKEN
              - name: SKILLHUB_API_KEY
                valueFrom:
                    secretKeyRef:
                        name: scraper-secrets
                        key: SKILLHUB_API_KEY
              volumeMounts:
                - name: bitbucket-ssh-key
                  mountPath: /home/scraper/ssh
                  readOnly: true
                - name: 
                  mountPath: /home/scraper/ssh
                  readOnly: true
            volumes:
              - name: bitbucket-ssh-key
                secret:
                    secretName: bitbucket-ssh-key
              - name: 
                secret:
                    secretName: 

    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
          automatic: true
          containerNames:
          - scraper
          from:
              kind: ImageStreamTag
              name: "scraper:latest"
